TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'M12.Foundation': TRUE

#    userInterface:
#      requireJsPathMapping:
#        'M12.Foundation/Inspector/Editors': 'resource://M12.Foundation/Public/JavaScript/Neos/Inspector/Editors'

    nodeTypes:
      groups:
        foundationStructure:
          position: 10
          label: 'Foundation - Structure'
        foundationNavigation:
          position: 20
          label: 'Foundation - Navigation'
        foundationMedia:
          position: 30
          label: 'Foundation - Media'
        foundationContent:
          position: 40
          label: 'Foundation - Content'
        foundationForms:
          position: 50
          label: 'Foundation - Forms'
        foundationButtons:
          position: 60
          label: 'Foundation - Buttons'
        foundationCalloutsPrompts:
          position: 70
          label: 'Foundation - Callouts & Prompts'


M12:
  Foundation:
    gridSize: 12

    devices:
      small:
        label: 'Small device'
      medium:
        label: 'Medium device'
      large:
        label: 'Large device'

    # @see AbstractGridNodeTypePostprocessor which utilizes these settings
    # to generate required properties for M12.Foundation:Column node type
    gridSettings:
      size:
        label: 'Grid column width'
        cssClassSuffixes: [ '-' ]         # DEVICE-X, eg: small-X, medium-Y, large-Z
        appliedPerColumn: true
        uiInspectorGroup: grid
      offset:
        label: 'Grid column offset'
        cssClassSuffixes: [ '-offset-' ]  # DEVICE-offset-X, eg: small-offset-X, medium-offset-Y, large-offset-Z
        appliedPerColumn: true
        uiInspectorGroup: grid
      pushPull:
        label: 'Grid column push / pull'
        cssClassSuffixes: [ '-push-', '-pull-' ]    # DEVICE-push-X, eg: small-push-X, medium-push-Y, large-push-Z
        appliedPerColumn: true
        uiInspectorGroup: grid
      align:
        label: 'Grid column align'
        cssClassSuffixes: [ '-centered', '-uncentered' ] # e.g. small-centered, large-centered
        appliedPerColumn: false
        uiInspectorGroup: grid
      resetOrder:
        label: 'Grid column reset order'
        cssClassSuffixes: [ '-reset-order' ]  # e.g. small-reset-order
        appliedPerColumn: false
        uiInspectorGroup: grid

    # @see AbstractGridNodeTypePostprocessor which utilizes these settings
    # to generate required properties for M12.Foundation:BlockGrid node type
    blockGridSettings:
      itemsPerRow:
        label: 'Number of items per row'
        cssClassSuffixes: [ '-block-grid-' ]    # DEVICE-block-grid-X, eg: small-block-grid-X, medium-block-grid-Y, large-block-grid-Z
        appliedPerColumn: true
        uiInspectorGroup: grid
        defaults: # default values per-device
          - small-block-grid-1
          - medium-block-grid-2
          - large-block-grid-3
